config/routes.rb
Coryslist::Application.routes.draw do
  get "dashboard", to: 'dashboard#index', as: 'dashboard'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'index', to: 'home#index', as: 'index'
  get 'list', to: 'list', as: 'lists'
  get 'task', to: 'task', as: 'tasks'

  match 'task/new' => 'task#new'

  root :to => "home#index"
  resources :users
  resources :sessions
  resources :list
  resources :task

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :category, :description, :title
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :priority, :title, :list_id
  belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :lists, dependent: :destroy
	has_many :tasks, through: :lists

	attr_accessible :email, :password, :password_confirmation

	validates_uniqueness_of :email

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
  	redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authorize
  def index
  	@lists = List.where(:user_id => current_user.id)
  	@list = List.new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
	before_filter :authorize

	def new
		@list = List.new
	end

	def create
  	@list = List.new(params[:list])
  	@list.user_id = current_user.id
	  if @list.save
	  	redirect_to dashboard_url, :notice => "List Created!"
	  else 
	  	render dashboard_url
	  end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to dashboard_path, notice: "Logged in!"
  	else
  		flash.now.alert = "Email or password is invalid"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
	before_filter :authorize
	
	def new
		@task = Task.new
	end

	def create
		list = List.find(params[:task][:list_id])
		if  current_user.id == list.user_id
			@task = Task.new(params[:task])
			@task.status = false
			@task.save
		end

		respond_to do |format|
			format.html{redirect_to dashboard_path}
			format.js
		end
	end

	def edit
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		redirect_to dashboard_path
	end

	def update
		@task = Task.find(params[:id])
		if @task.status == nil
			@task.status = true
		elsif @task.status == true
			@task.status = false
		elsif @task.status == false
			@task.status = true
		end
		@task.save
		redirect_to dashboard_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		redirect_to root_url, :notice => "Signed_up!"
  	else 
  		render "new"
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div id="dashboard-container">
	<h1>My To Do Lists</h1>
	<p>Create New List</p>
	
</div>


  <%= form_for(List.new) do |f| %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>
    <div class="actions"><%= f.submit "Create List" %></div>
  <% end %>

<div id ="lists-container">
	<% @lists.each do |l| %>
		<div class="list-container" id="list-container<%=l.id %>">
			<div class="list-title">
				<%= l.title %>
			</div>
			<div class="list-description">
	  			<%= l.description %>
	  		</div>
	  		<div class="task-create-link" id="task-create-link<%=l.id%>">
	  			<%= link_to "Add task", new_task_path(:list_id => l.id), :method => :post, remote:true %>
	  		</div>
	  		<div class="tasks-container">
	  			<% l.tasks.order(:created_at).each do |t| %>
	  				<% if t.status==true %>
		  				<div class="task-container task-completed">
				  			<div class="task-mark-complete">
				  				<%= form_for(t) do |f| %>
	  								<div class="update-task">
	  									<%= f.submit ""%>
	  								</div>
								<% end %>
				  			</div>
			  			<% else %>
			  				<div class="task-container">
					  			<div class="task-mark-complete">
					  				<%= form_for(t) do |f| %>
		  								<div class="update-task">
		  									<%= f.submit ""%>
		  								</div>
									<% end %>
					  			</div>
			  			<% end %>
			  			<div class="task-title">
			  				<%= t.title %>
			  			</div>
			  			<div class="task-delete-link">
			  				<%= link_to "x", t, method: :delete, data: {confirm: "Are you sure you want to delete this task?"} %>
			  			</div>
			  			<div class="task-description">
			  				<%= t.description %>
			  			</div>
			  			<div class="task-edit-link">
			  			</div>
		  			</div>
		  			<br></br>
	  			<% end %>
	  		</div>
  		</div>
  	<% end %>
</div>

app/views/home/index.html.erb
<div id="home-container">
	<div id="home-logo">Cory's List</div>
	<div id="home-slogan">Get some shi* done!</div>

	<div id="home-login">
	<h2>Log In</h2>

		<%= form_tag sessions_path do %>
		  <div class="field">
		    <%= label_tag :email %><br />
		    <%= text_field_tag :email, params[:email] %>
		  </div>
		  <div class="field">
		    <%= label_tag :password %><br />
		    <%= password_field_tag :password %>
		  </div>
		  <div class="actions"><%= submit_tag "Log In" %></div>
		<% end %>
	</div>
	<div id="home-signup-container">
		<div id="home-signup"><%= link_to "Sign Up", signup_path  %>
		</div>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coryslist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">  
  <div class="navbar-inner">  
    <div class="container">
    	<div id="navbar-logo">
    		<% if current_user %>
    			<%= link_to "Cory's List", dashboard_path %>
    		<% else %>
    			<%= link_to "Cory's List", index_path %>
    		<% end %>
    	</div>
      <div id="navbar-logout">
        <% if current_user %>
          <%= link_to "Logout", logout_path %>
        <% else %>
          
        <% end %>
      </div>
    </div>  
  </div>  
</div>  

<%= yield %>

</body>
</html>

app/views/list/new.html.erb
  <%= form_for @lists do |f| %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>
    <div class="actions"><%= f.submit "Create List" %></div>
  <% end %>

app/views/task/_form.html.erb
<div id="task-create-form<%=params[:list_id]%>">  

  <%= form_for @task, remote: true do |f| %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>
    <%= f.hidden_field :list_id, :value => params[:list_id] %>
    <div class="actions"><%= f.submit "Create Task" %></div>
  <% end %>
</div>

app/views/task/_task.html.erb
<div class="task-container">
	<div class="task-mark-complete">
		<%= form_for(t) do |f| %>
			<div class="update-task">
				<%= f.submit ""%>
			</div>
		<% end %>
	</div>

	<div class="task-title">
		<%= t.title %>
	</div>
	<div class="task-delete-link">
		<%= link_to "x", t, method: :delete, data: {confirm: "Are you sure you want to delete this task?"} %>
	</div>
	<div class="task-description">
		<%= t.description %>
	</div>
	<div class="task-edit-link"> 

app/views/task/create.js.erb
divId = '<%= j params[:list_id] %>';
console.log(divId)
$('#task-create-form'+divId).remove();
$('.list-container'+divId).append('<%= j render partial: "task", locals: {t: @task} %>');

app/views/task/new.html.erb
<div id="task-create-form">  

  <%= form_for @task do |f| %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>
    <%= f.hidden_field :list_id, :value => params[:list_id] %>
    <div class="actions"><%= f.submit "Create Task" %></div>
  <% end %>
</div>

app/views/task/new.js.erb
divId = <%= params[:list_id] %>;
$('#task-create-link'+divId).hide().after('<%= j render ("form") %>');

app/views/users/new.html.erb
<div id="signup-container">
  <h1>Sign Up</h1>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit "Sign Up" %></div>
  <% end %>

</div>